int main() 
{ 
  __asm__ __volatile__ ( 
                         "li ra,0x6b8b4567;"
                         "li sp,0x327b23c6;"
                         "li gp,0x643c9869;"
                         "li tp,0x66334873;"
                         "li t0,0x74b0dc51;"
                         "li t1,0x19495cff;"
                         "li t2,0x2ae8944a;"
                         "li s0,0x625558ec;"
                         "li s1,0x238e1f29;"
                         "li a0,0x46e87ccd;"
                         "li a1,0x3d1b58ba;"
                         "li a2,0x507ed7ab;"
                         "li a3,0x2eb141f2;"
                         "li a4,0x41b71efb;"
                         "li a5,0x79e2a9e3;"
                         "li a6,0x7545e146;"
                         "li a7,0x515f007c;"
                         "li s2,0x5bd062c2;"
                         "li s3,0x12200854;"
                         "li s4,0x4db127f8;"
                         "li s5,0x216231b;"
                         "li s6,0x1f16e9e8;"
                         "li s7,0x1190cde7;"
                         "li s8,0x66ef438d;"
                         "li s9,0x140e0f76;"
                         "li s10,0x3352255a;"
                         "li s11,0x109cf92e;"
                         "li t3,0xded7263;"
                         "li t4,0x7fdcc233;"
                         "li t5,0x1befd79f;"
                         "li t6,0x41a7c4c9;"
                       );
  __asm__ __volatile__ ( "csrrwi s9,0x7c1, 0x1;" 
                         "nop;"
                         "nop;"
                         "nop;"
                       );
  __asm__ __volatile__ ( 
                         "slli ra, ra, 1;"
                          "slli sp, sp, 2;"
                          "slli gp, gp, 3;"
                          "slli tp, tp, 4;"
                          "slli t0, t0, 5;"
                          "slli t1, t1, 6;"
                          "slli t2, t2, 7;"
                          "slli s0, s0, 8;"
                          "slli s1, s1, 9;"
                          "slli a0, a0, 10;"
                          "slli a1, a1, 11;"
                          "slli a2, a2, 12;"
                          "slli a3, a3, 13;"
                          "slli a4, a4, 14;"
                          "slli a5, a5, 15;"
                          "slli a6, a6, 16;"
                          "slli a7, a7, 17;"
                          "slli s2, s2, 18;"
                          "slli s3, s3, 19;"
                          "slli s4, s4, 20;"
                          "slli s5, s5, 21;"
                          "slli s6, s6, 22;"
                          "slli s7, s7, 23;"
                          "slli s8, s8, 24;"
                          "slli s9, s9, 25;"
                          "slli s10, s10, 26;"
                          "slli s11, s11, 27;"
                          "slli t3, t3, 28;"
                          "slli t4, t4, 29;"
                          "slli t5, t5, 30;"
                          "slli t6, t6, 31;"
                          "slli ra, ra, 1;"
                          "slli sp, sp, 2;"
                          "slli gp, gp, 3;"
                          "slli tp, tp, 4;"
                          "slli t0, t0, 5;"
                          "slli t1, t1, 6;"
                          "slli t2, t2, 7;"
                          "slli s0, s0, 8;"
                          "slli s1, s1, 9;"
                          "slli a0, a0, 10;"
                          "slli a1, a1, 11;"
                          "slli a2, a2, 12;"
                          "slli a3, a3, 13;"
                          "slli a4, a4, 14;"
                          "slli a5, a5, 15;"
                          "slli a6, a6, 16;"
                          "slli a7, a7, 17;"
                          "slli s2, s2, 18;"
                          "slli s3, s3, 19;"
                          "slli s4, s4, 20;"
                          "slli s5, s5, 21;"
                          "slli s6, s6, 22;"
                          "slli s7, s7, 23;"
                          "slli s8, s8, 24;"
                          "slli s9, s9, 25;"
                          "slli s10, s10, 26;"
                          "slli s11, s11, 27;"
                          "slli t3, t3, 28;"
                          "slli t4, t4, 29;"
                          "slli t5, t5, 30;"
                          "slli t6, t6, 31;"
                          "slli ra, ra, 1;"
                          "slli sp, sp, 2;"
                          "slli gp, gp, 3;"
                          "slli tp, tp, 4;"
                          "slli t0, t0, 5;"
                          "slli t1, t1, 6;"
                          "slli t2, t2, 7;"
                          "slli s0, s0, 8;"
                          "slli s1, s1, 9;"
                          "slli a0, a0, 10;"
                          "slli a1, a1, 11;"
                          "slli a2, a2, 12;"
                          "slli a3, a3, 13;"
                          "slli a4, a4, 14;"
                          "slli a5, a5, 15;"
                          "slli a6, a6, 16;"
                          "slli a7, a7, 17;"
                          "slli s2, s2, 18;"
                          "slli s3, s3, 19;"
                          "slli s4, s4, 20;"
                          "slli s5, s5, 21;"
                          "slli s6, s6, 22;"
                          "slli s7, s7, 23;"
                          "slli s8, s8, 24;"
                          "slli s9, s9, 25;"
                          "slli s10, s10, 26;"
                          "slli s11, s11, 27;"
                          "slli t3, t3, 28;"
                          "slli t4, t4, 29;"
                          "slli t5, t5, 30;"
                          "slli t6, t6, 31;"
                          "slli ra, ra, 1;"
                          "slli sp, sp, 2;"
                          "slli gp, gp, 3;"
                          "slli tp, tp, 4;"
                          "slli t0, t0, 5;"
                          "slli t1, t1, 6;"
                          "slli t2, t2, 7;"
                          "slli s0, s0, 8;"
                          "slli s1, s1, 9;"
                          "slli a0, a0, 10;"
                          "slli a1, a1, 11;"
                          "slli a2, a2, 12;"
                          "slli a3, a3, 13;"
                          "slli a4, a4, 14;"
                          "slli a5, a5, 15;"
                          "slli a6, a6, 16;"
                          "slli a7, a7, 17;"
                          "slli s2, s2, 18;"
                          "slli s3, s3, 19;"
                          "slli s4, s4, 20;"
                          "slli s5, s5, 21;"
                          "slli s6, s6, 22;"
                          "slli s7, s7, 23;"
                          "slli s8, s8, 24;"
                          "slli s9, s9, 25;"
                          "slli s10, s10, 26;"
                          "slli s11, s11, 27;"
                          "slli t3, t3, 28;"
                          "slli t4, t4, 29;"
                          "slli t5, t5, 30;"
                          "slli t6, t6, 31;"
                       );
  __asm__ __volatile__ ( "ms: csrrwi s9,0x7c1, 0x0;"
                       );
} 
